// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c47d24f9-0c42-4a08-97aa-6d9d9308f462",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_miMYrfOdP",
    "aws_user_pools_web_client_id": "murjs8l06i0f4f5se17jvs3ga",
    "aws_content_delivery_bucket": "reactboilerplate-20181002143645--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://reactboilerplate-20181002143645--hostingbucket.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
